### ISSUE TITLE
Node 12 does not support null coalescing operator

### ISSUE THREAD

**Issue by Kevmo92** [forcedotcom/kit#81]
The recent changes made https://github.com/forcedotcom/kit/compare/1.6.1...1.7.0

are causing old versions of sfdx like `sfdx-cli@7.96.1` to no longer work with node 12.

```
sfdx version --verbose --json
/Users/kevinwatson/.fnm/node-versions/v12.22.12/installation/lib/node_modules/sfdx-cli/node_modules/@salesforce/kit/lib/env.js:18
    constructor(store = process?.env || {}) {
                                ^

SyntaxError: Unexpected token '.'
    at new Script (vm.js:88:7)
    at NativeCompileCache._moduleCompile (/Users/kevinwatson/.fnm/node-versions/v12.22.12/installation/lib/node_modules/sfdx-cli/node_modules/v8-compile-cache/v8-compile-cache.js:240:18)
    at Module._compile (/Users/kevinwatson/.fnm/node-versions/v12.22.12/installation/lib/node_modules/sfdx-cli/node_modules/v8-compile-cache/v8-compile-cache.js:184:36)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (/Users/kevinwatson/.fnm/node-versions/v12.22.12/installation/lib/node_modules/sfdx-cli/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    at Object.<anonymous> (/Users/kevinwatson/.fnm/node-versions/v12.22.12/installation/lib/node_modules/sfdx-cli/node_modules/@salesforce/kit/lib/index.js:25:14)
    at Module._compile (/Users/kevinwatson/.fnm/node-versions/v12.22.12/installation/lib/node_modules/sfdx-cli/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
```

**Comment by Kevmo92** [comment]
If `process?.env` could be reverted to `(process && process.env)` that should work?

**Comment by jtaylormayfield** [comment]
Maybe increasing the required version of NodeJS for a NodeJS project should result in a major version increment.

**Comment by cromwellryan** [comment]
[Node 12 hit end-of-life on 2022-04-30](https://github.com/nodejs/release#end-of-life-releases). `sfdx` no longer supports Node 12 as a result.

There is a [workaround detailed](https://github.com/forcedotcom/cli/issues/1741#issuecomment-1268582505) in forcedotcom/cli#1741 if you are unable to upgrade your Node version.

Also, 7.96 is well over a year old. We would encourage you to upgrade your version of `sfdx`.
